const $=s=>document.querySelector(s);let toastTimer,lost=false,reportCount=4;
function toast(m){$("#toast").textContent=m;$("#toast").classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("#toast").classList.remove("show"),2800)}
$("#photoReady").addEventListener("change",e=>{const done=e.target.checked;$("#photoItem").classList.toggle("done",done);$("#photoItem").textContent=done?"託運前照片已完成":"缺少託運前照片";$("#readyScore").textContent=done?"100%":"75%";$("#setupState").textContent=done?"4 / 4 完成":"3 / 4 完成"});
$("#activateTrip").addEventListener("click",()=>{if(!$("#photoReady").checked){toast("旅程已啟用，但仍建議補拍託運前外觀與內容物清單。")}else toast("旅程守護已啟用；感測器事件不等於官方行李追蹤。");$("#syncTime").textContent="現在"});
$("#expectedMove").addEventListener("click",()=>{document.querySelector(".live-alert").style.opacity=".58";$("#eventLog").insertAdjacentHTML("afterbegin","<div><time>現在</time><p><strong>使用者確認為正常移動</strong><small>事件已結案，不啟用遺失模式</small></p></div>");toast("事件已標記為正常移動。")});
$("#cannotFind").addEventListener("click",()=>{lost=true;$("#lostTitle").textContent="準備啟用遺失模式";$("#startLostMode").disabled=false;toast("請先查看轉盤與特殊行李區，並立即聯絡行李服務櫃檯。")});
$("#startLostMode").addEventListener("click",()=>{$("#lostTitle").textContent="遺失模式已啟用";$("#startLostMode").disabled=true;$("#startLostMode").textContent="事件時間線持續記錄中";$("#eventLog").insertAdjacentHTML("afterbegin","<div><time>現在</time><p><strong>使用者啟用遺失模式</strong><small>等待航空公司申報參考編號</small></p></div>");toast("已開始整理事件時間線；這不會自動向航空公司或警方申報。")});
$("#savePir").addEventListener("click",()=>{const value=$("#pirInput").value.trim();if(!value){toast("請先輸入航空公司提供的申報參考編號。");return}if(!$("#pirCheck").checked){$("#pirCheck").checked=true;reportCount++;$("#reportCount").textContent=`${reportCount} / 7`}toast("申報參考編號已加入資料包。")});
$("#pirCheck").addEventListener("change",e=>{reportCount+=e.target.checked?1:-1;$("#reportCount").textContent=`${reportCount} / 7`});
$("#buildPackage").addEventListener("click",()=>{const pir=$("#pirInput").value.trim(),photo=$("#photoReady").checked;if(!pir||!photo){$("#packageState").textContent=`仍缺少${!pir?"航空公司申報編號":""}${!pir&&!photo?"與":""}${!photo?"託運前照片":""}。`;toast("資料包可預覽，但仍有必要證明未完成。")}else{$("#packageState").textContent="資料包預覽完成；實際採認仍依航空公司、警方與保險條款。";toast("資料包預覽已完成，不會自動送出理賠申請。")}});
document.querySelectorAll("[data-scroll]").forEach(b=>b.addEventListener("click",()=>$(b.dataset.scroll)?.scrollIntoView({behavior:"smooth"})));
